site_name: mostlyai-qa
repo_url: "https://github.com/mostly-ai/mostly-python"
repo_name: "mostly-ai/mostly-python"
theme:
  name: material
  logo: logo.png
  favicon: favicon.png

  palette:
  - media: "(prefers-color-scheme)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb
      name: "Switch to light mode"
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: "Switch to dark mode"
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: pink
    accent: pink
    toggle:
      icon: material/lightbulb-auto-outline
      name: "Switch to system preference"

  features:
    - navigation.instant
    - navigation.instant.prefetch
#    - navigation.tabs
#    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - search.share
    - content.code.select
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - toc.follow

nav:
  - Home: index.md
  - Metrics: metrics.md
  - API Reference: api.md
  - Examples: examples.md

extra:
  version:
    provider: mike

plugins:
  - search
  - mike
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_root_heading: true
            show_docstring: true
            show_source: false
            show_signature: true
            separate_signature: true
            show_docstring_examples: true
#            show_signature_annotations: true
#            line_length: 60
            extensions:
            - griffe_fieldz
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
