site_name: "mostlyai-qa"
site_url: "https://mostly-ai.github.io/mostlyai-qa/"
repo_url: "https://github.com/mostly-ai/mostlyai-qa"
repo_name: "mostly-ai/mostlyai-qa"

theme:
  name: material
  logo: logo.png
  favicon: favicon.png
  font:
    text: Lato
  features:
    - navigation.top
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.select
    - content.code.copy
    - navigation.footer

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

nav:
  - Getting started: index.md
  - API Reference: api.md
  - Metrics: metrics.md
  - Examples: examples.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_root_heading: true
            show_bases: false
            show_docstring: true
            show_source: false
            show_signature: true
            separate_signature: true
            show_docstring_examples: true
            docstring_section_style: table
            extensions:
            - griffe_fieldz
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
