name: Lint Check

on: [workflow_call]

jobs:
  pre-commit-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Setup | uv Installation
        uses: astral-sh/setup-uv@v5

      - name: Lint | Ruff
        run: |
          uv sync --package ruff --frozen
          uv run --no-sync ruff check .
          uv run --no-sync ruff format --check .
